spring:
  application:
    name: rubicon
  datasource:
#    url: jdbc:postgresql://database-1.c74ems0qcjiq.ap-south-1.rds.amazonaws.com:5432/rubicon
#    username: postgres
#    password: rubicon1916

#    url: jdbc:postgresql://localhost:5432/rubicon
#    username: postgres
#    password: 1916
    url: jdbc:postgresql://15.252.182.241:5432/rubicon
    username: rub_user
    password: rubicon1916
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 9090

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
